version: "3.9"

services:
  db:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_NAME:-spa}
      MYSQL_USER: ${DB_USER:-spa}
      MYSQL_PASSWORD: ${DB_PASSWORD:-spa}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","","--appendonly","no"]
    # ports:
    #   - "6379:6379"
    # volumes:
    #   - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      DB_ENGINE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DEBUG: "True"
      RUN_COLLECTSTATIC: "0"
      REDIS_URL: redis://redis:6379/0

      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data:
    driver: local