"""
Django settings for spa_comments project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import mimetypes
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ROOT_DIR = BASE_DIR.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "") != "False"

ALLOWED_HOSTS = \
    [h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",")
     if h.strip()]
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

# CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")

CORS_ALLOWED_ORIGINS = \
    [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
     if o.strip()]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

PAGE_SIZE = int(os.getenv("PAGE_SIZE", 2))

FRONTEND_BACKEND_URL = os.getenv("FRONTEND_BACKEND_URL")

RECAPTCHA_VERIFY_URL = os.getenv("RECAPTCHA_VERIFY_URL")

# reCAPTCHA keys
RECAPTCHA_SITE_KEY = os.getenv("RECAPTCHA_SITE_KEY")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY")

ASGI_APPLICATION = "spa_comments.asgi.application"

REDIS_URL = os.getenv("REDIS_URL")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "channels",
    "users",
    "comments",
    "storages",
]

AUTH_USER_MODEL = "users.SpaUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "spa_comments.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "spa_comments.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite")  # "sqlite" | "mysql"
# if DB_ENGINE == "mysql":
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.mysql",
#             "NAME": os.getenv("DB_NAME", "spa"),
#             "USER": os.getenv("DB_USER", "spa"),
#             "PASSWORD": os.getenv("DB_PASSWORD", "spa"),
#             "HOST": os.getenv("DB_HOST", "db"),
#             "PORT": os.getenv("DB_PORT", "3306"),
#             "OPTIONS": {
#                 "charset": "utf8mb4",
#                 "init_command": "SET sql_mode='STRICT_ALL_TABLES'"
#             },
#         }
#     }
# else:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": os.getenv("SQLITE_PATH", BASE_DIR / "db.sqlite3"),
#         }
#     }
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DB_ENGINE = os.getenv("DB_ENGINE", "sqlite")  # "sqlite" | "mysql"
    if DB_ENGINE == "mysql":
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": os.getenv("DB_NAME", "spa"),
                "USER": os.getenv("DB_USER", "spa"),
                "PASSWORD": os.getenv("DB_PASSWORD", "spa"),
                "HOST": os.getenv("DB_HOST", "db"),
                "PORT": os.getenv("DB_PORT", "3306"),
                "OPTIONS": {
                    "charset": "utf8mb4",
                    "init_command": "SET sql_mode='STRICT_ALL_TABLES'",
                },
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": os.getenv("SQLITE_PATH", BASE_DIR / "db.sqlite3"),
            }
        }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "100/day", "user": "1000/day"},
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS":
        "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": PAGE_SIZE,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.OrderingFilter",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "SPA Comments API",
    "DESCRIPTION": "Documentation for SPA Comments API.",
    "VERSION": "1.0.0",
    "SERVER_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "defaultModelRendering": "model",
        "defaultModelsExpandDepth": 2,
        "defaultModelExpandDepth": 2,
    },
    "SERVERS": [
        {"url":
         os.getenv("PUBLIC_API_BASE", "http://localhost:8000"),
         "description": "API"
         }
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Bratislava"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

mimetypes.add_type("image/webp", ".webp", True)

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    # locally without redis
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security for production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False") == "True"
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"


# === Supabase Storage (MEDIA) ===
STORAGES = {
    "default": {
        "BACKEND": "spa_comments.storage_backends.SupabaseMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

AWS_S3_ENDPOINT_URL = os.getenv("SUPABASE_S3_ENDPOINT")
AWS_S3_REGION_NAME = os.getenv("SUPABASE_S3_REGION", "us-east-1")
AWS_ACCESS_KEY_ID = os.getenv("SUPABASE_S3_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("SUPABASE_S3_SECRET")
AWS_STORAGE_BUCKET_NAME = os.getenv("SUPABASE_MEDIA_BUCKET", "spa-comments-media")

# for Supabase S3:
AWS_S3_ADDRESSING_STYLE = "path"   # forcePathStyle: true
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = True

# It's better not to set up an ACL, but to create a public bucket at the Supabase level.
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False

# MEDIA_URL will be built manually through CDN (см. storage_backends.py)
SUPABASE_PROJECT_REF = os.getenv("SUPABASE_PROJECT_REF")
if SUPABASE_PROJECT_REF:
    MEDIA_URL = (
        f"https://{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/object/public/"
        f"{os.getenv("SUPABASE_MEDIA_BUCKET", "spa-comments-media")}/"
    )
