# Generated by Django 5.2.6 on 2025-09-07 13:09

from django.db import migrations, models
import users.models

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spauser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.avatars_file_path,
                verbose_name="Avatar",
            ),
        ),
    ]
